#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Refresh sudo session
alias sudo='sudo -v; sudo '

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv --reflink=auto --sparse=auto" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkdir="mkdir -pv" \
	youtube-dl="youtube-dl --add-metadata -i" \
	ffmpeg="ffmpeg -hide_banner" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ip="ip -color=auto"
	info='info --vi-keys' \
	gdb="gdb -q" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"

[ -x "$(command -v highlight)" ] && ccat="highlight --out-format=ansi | less --quit-if-one-screen"
[ -x "$(command -v bat)" ] && ccat="bat"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="shutdown -h now"
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR"
	mkd="mkdir" \
	yt="youtube-dl" \

if [[ "$UNAME" == *"Linux"* ]]; then
	alias open="systemd-run -dq --user xdg-open"
fi

# Advanced aliases
alias \
	dotfiles='git --git-dir=$HOME/.dotfiles --work-tree=$HOME' \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	yta="yt -x -f bestaudio/best"
