#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx='startx $XINITRC'

# Refresh sudo session
alias sudo='sudo -v; sudo '

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv --reflink=auto --sparse=auto" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkdir="mkdir -pv" \
	youtube-dl="yt-dlp --embed-metadata -i" \
	ffmpeg="ffmpeg -hide_banner" \
	info='info --vi-keys' \
	gdb="gdb -q" \
	#tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"
[ -x "$(command -v highlight)" ] && ccat="highlight --out-format=ansi | less --quit-if-one-screen"
[ -x "$(command -v bat)" ] && ccat="bat"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	mkd="mkdir" \
	yt="youtube-dl" \
	pd="popd" \
	p="pnpm" \

if [[ "$UNAME" == *"Linux"* ]]; then
	alias open="systemd-run -dq --user xdg-open"
fi

# Advanced aliases
alias \
	dotfiles='git --git-dir=$HOME/.dotfiles --work-tree=$HOME' \
	magit="nvim -c MagitOnly" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail"
