#!/bin/zsh

# profile file. Runs on login. Environmental variables are set here.

# Platform variable
export UNAME="$(uname -s)"

# Use GNU Coreutils on macOS
if [[ "$UNAME" = "Darwin" && -d "/usr/local/opt/coreutils/libexec/gnubin" ]]; then
	export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
fi

# Adds `~/.local/bin` to $PATH
if [ -d $HOME/.local/bin ]; then
    export PATH=$PATH$( find $HOME/.local/bin -type d -printf ":%p" )
fi

# Default editor:
if [ -x $(command -v nvim) ]; then
    export EDITOR="nvim"
else if [ -x $(command -v vim) ]; then
    export EDITOR="vim"
fi

# Use GnuPG as ssh-agent & clean up gpg home
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

# ~/ Clean-up:
if [ -z "$XDG_CACHE_HOME" ]; then
    export XDG_CACHE_HOME="$HOME/.cache"
fi

if [ -z "$XDG_DATA_HOME" ]; then
    export XDG_DATA_HOME="$HOME/.local/share"
fi

if [ -z "$XDG_CONFIG_HOME" ]; then
    export XDG_CONFIG_HOME="$HOME/.config"
fi

if [ -z "$XDG_RUNTIME_DIR" ]; then
    export XDG_RUNTIME_DIR="$XDG_CACHE_HOME"
fi

export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
export TMUX_TMPDIR="${XDG_RUNTIME_DIR}"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export KUBECONFIG="${XDG_DATA_HOME:-$HOME/.local/share}/kube"
export SQLITE_HISTORY="${XDG_CACHE_HOME:-$HOME/.cache}/sqlite_history"

# Other program settings:
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"

[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && shortcuts >/dev/null 2>&1 &
